---
name: "PSN Trophies"
author: "John Losito"
description: "Adds your PlayStation Trophies to your README"

inputs:
  NPSSO:
    description: "Playstation auth token"
    required: true
  README_PATH:
    description: "Path to the readme file"
    required: false
    default: "./README.md"

runs:
  using: 'node16'
  main: 'index.js'
